### ISSUE TITLE
Non-JSON responses cause an immediate exception

### ISSUE THREAD

**Issue by CreeperPookie** [SebaOfficial/pantry-cloud#4]
Something I've noticed in my experiments of the Pantry API (https://documenter.getpostman.com/view/3281832/SzmZeMLC) is that sometimes it simply does not give a JSON response; instead, it will just send back raw plain text - *even if* the `Content-Type` is set to `application/json`.
A good example of this is creating a basket or running into the rate limits, where the server will send back something similar to `Your Pantry was updated with basket: <basket>!` and `Pantry is a free service and in order to maintain availability for all users requests have been limited. Please
try again later.`, respectfully; they even show this to an extent in their documentation, though it's not plainly stated.

The problem with that is directly after [Client.php](https://github.com/SebaOfficial/pantry-cloud/blob/main/src/Client.php#L58) sends a request, it feeds the data directly into `json_decode`. For a normal response this wouldn't be a problem, but for a plain-text response this results in the function returning null (as the plain text is not JSON), and causes the aforementioned exception: `PHP Fatal error: Uncaught TypeError: Pantry\Client::request(): Return value must be of type object, null returned in <project>/vendor/seba/pantry/src/Client.php on line 58`

**Comment by SebaOfficial** [comment]
It should now be fixed (on `v2.0.1`) would you mind checking it out?
Thanks for your feedback btw

**Comment by CreeperPookie** [comment]
> It should now be fixed (on `v2.0.1`) would you mind checking it out? Thanks for your feedback btw

@SebaOfficial well just got the chance to test it, and well, it still causes an error when creating a basket: `Uncaught TypeError: Pantry\Client::request(): Return value must be of type object, null returned in <project>\vendor\seba\pantry\src\Client.php:61`; honestly I don't think the `request` function is able to return null in any situation lol

I also looked at the new code and although it's definitely an improvement, I should clarify that the plain text responses are not *necessarily* always errors; for example, creating or deleting a basket will result in a plain text response; however, they indicate *success*. 
I still will never understand why Pantry decided to give a plain text response at all honestly, especially considering literally everything else has a response as JSON

for the fix, I would say to first check if the decoded response is not JSON and if the response is a 2xx success, then return the equivalent of a `{}` JSON or similar; otherwise, throwing an error does makes sense (such as in the case of 429 too many requests)

**Comment by SebaOfficial** [comment]
@CreeperPookie you're right, I'll work on it ASAP. I'll keep you updated.
Tbh it's a bit strange on the pantry's side to respond with non JSON data, I'll investigate it deeper.

**Comment by CreeperPookie** [comment]
> @CreeperPookie you're right, I'll work on it ASAP. I'll keep you updated.

alright lol

> Tbh it's a bit strange on the pantry's side to respond with non JSON data, I'll investigate it deeper.

yeah that's what I always thought; it really doesn't any sense, especially since nearly everything else responds with JSON by default

**Comment by SebaOfficial** [comment]
@CreeperPookie I've personally tested the new version (`v2.0.2`) and it should now work with every text responses. Would you still mind testing it yourself? Thanks.

**Comment by CreeperPookie** [comment]
> [@CreeperPookie](https://github.com/CreeperPookie) I've personally tested the new version (`v2.0.2`) and it should now work with every text responses. Would you still mind testing it yourself? Thanks.

@SebaOfficial seems pretty solid in my testing, both creating and deleting a basket does not resolve in a terminating error! I also tested 429 too many requests too, and that does still give an error; however, it *is* being wrapped in a [RequestException](https://github.com/SebaOfficial/pantry-cloud/blob/main/src/Exceptions/RequestException.php), so I would say that's fair.

Also, I did take a look at 8e84dcc as well, the solution seems pretty solid; however, from the [PHP Documentation](https://www.php.net/manual/en/function.json-decode.php#refsect1-function.json-decode-returnvalues), the function returns `null` if it cannot parse the JSON, but doesn't directly throw an exception; the exception probably comes from trying to *return* null, which is what is subsequently caught. 
Either way it does appear to work correctly, but just something to keep in mind :D

**Comment by SebaOfficial** [comment]
Cool, I'll checkout your pull request #7, for now I'll close this issue.
